TYPE_ALLIED = 0
TYPE_ENEMY_SMALL = 1
TYPE_ENEMY_LARGE = 2

SYM_PLAYER = '@'
SYM_FIGHTER = 'F'
SYM_AD_FIGHTER = 'A'
SYM_CRUISER = 'C'
SYM_BATTLESHIP = 'B'

SYM_RESUPPLY = '$'

PLANET_BARREN = 0
PLANET_HOSTILE = 1
PLANET_FRIENDLY = 2

PLANET_TYPES = [PLANET_BARREN, PLANET_HOSTILE, PLANET_FRIENDLY]

LOCAL_ENERGY_COST = 100
SECTOR_ENERGY_COST = 500
